import "../globals.css";
import React from 'react'
import { GiHamburgerMenu } from "react-icons/gi";
import { FaRegUserCircle } from "react-icons/fa";
import { FaRegUser } from "react-icons/fa";
import { CiSearch } from "react-icons/ci";
import Link from 'next/link';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className=" bg-white" >

                <div className='h-[65px]  w-screen px-4 flex items-center bg-white'>
                    <div className='flex gap-4 items-center w-[255px]'>
                        <img src="https://bhuvan.nrsc.gov.in/home/images/bhuvan-logo.png" alt="" className='h-[35px]' />
                        <GiHamburgerMenu className='text-xl' />
                    </div>
                    <div className='flex w-[calc(100%-255px)] items-center justify-between text-sm'>
                        <ul className='flex justify-around w-[30%]  min-w-[300px]'>
                            <li className='hover:underline cursor-pointer h-full'><Link href="/pages/home">Home</Link></li>
                            <li className='hover:underline cursor-pointer h-full'><Link href="/pages/about">About</Link></li>
                            <li className='hover:underline cursor-pointer h-full'><Link href="/pages/contact">Contact</Link></li>
                        </ul>
                        <ul className='flex justify-around items-center w-[30%]  min-w-[300px]'>
                            <li className='hover:underline cursor-pointer h-full'>Help</li>

                            <li className='hover:underline cursor-pointer h-full'> Login</li>
                            <FaRegUserCircle className='text-xl' />
                        </ul>
                    </div>
                </div>

                <main className='bg-white'>
                    {/* <nav className='h-[calc(100vh-64px)] fixed top-[65px] left-0  w-[255px] py-4'>

                        <ul className='  w-full text-xl font-light'>
                            <li>
                                <div className='flex items-center gap-4 font-normal w-full p-4'>
                                    <FaRegUser className='text-4xl' />
                                    <div>
                                        <h2 className='text-lg font-bold'>Jayvardhan Patil</h2>
                                        <p className='text-xs'>A student</p>
                                    </div>
                                </div>
                                <div className='p-4'>
                                    <div className='w-full h-[40px] border-2 flex  items-center text-sm pl-2 '>
                                        <div className='w-4/5 flex justify-center'>Type your query here</div>
                                        <div className='w-1/5 border-l-2 text-xl font-bold   h-full flex items-center justify-center'>
                                            <CiSearch />
                                        </div>
                                    </div>
                                </div>
                                <p className='px-4 text-base opacity-50'>Dash Menu</p>
                            </li>
                            <li className='px-4 py-2 cursor-pointer hover:bg-slate-200'>Home</li>
                            <li className='px-4 py-2 cursor-pointer hover:bg-slate-200'>About</li>
                            <li className='px-4 py-2 cursor-pointer hover:bg-slate-200'>Contact</li>
                            <li className='px-4 py-2 cursor-pointer hover:bg-slate-200'>Newsletter</li>
                            <li className='px-4 py-2 cursor-pointer hover:bg-slate-200'>Wiki</li>
                            <li className='px-4 py-2 cursor-pointer hover:bg-slate-200'>Contact</li>
                        </ul>
                    </nav> */}
                    {children}
                </main>
            </body>
        </html>
    )
}